# Generated by Django 5.1.15 on 2026-09-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_playlist_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('item_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.chapter')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('chapter', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('bunny', 'Bunny Stream')], default='youtube', max_length=20)),
                ('youtube_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bunny_library_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bunny_video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.IntegerField(default=0)),
                ('is_short', models.BooleanField(default=False)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('content_type', models.CharField(choices=[('Concept', 'Concept'), ('PYQ', 'PYQ'), ('Problem Solving', 'Problem Solving'), ('Advanced Problem', 'Advanced Problem'), ('Revision', 'Revision'), ('Strategy', 'Strategy'), ('Other', 'Other')], default='Other', max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Advanced', 'Advanced')], default='Medium', max_length=20)),
                ('pyq_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.chapter')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.playlist')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.topic')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('source', models.CharField(choices=[('youtube', 'YouTube Live'), ('managed', 'Managed Stream')], default='youtube', max_length=20)),
                ('stream_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='content.video')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
